language: node_js
sudo: false
cache:
  directories:
  - node_modules
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: Dzo9TpAVIva/Mz8aQnq41hy2zqhJoj9gkp/jnjYbo4zGPJ28wPFA7oFpkU3qM+sOaW8IAybwtKgno7Nbdb8Ty5sWKgOyEbR63fbSIsm/16FJZmrHNQB+uffX5XobY7pmKyGf+fAubi2pwcDppO0NUFAIXhdt4CjOxEv0X8AZfZlEguf5Q+2g1ZNJIpavC0AwCU7Cd6kl8Zt1ldkMUNxHOx8UxHUNwzdvb+SeqN69OPwA1Czpo7B9M3TZfrvTYur501RziEtOhSVldoavMQ2fA68G6yoqY/Ul2JzQhpw+WhzzxXgtphMe5aTL5hYtSqqkSHDkdV5410DLxnRdTuzDjToatn2NL4Qv0OIFC6ql9mfyHsSn9cgg7Nc/nIL6ZnTWSyYS3jC4itLO+Tf0rUKcBVAo5rJx47DJ8Ji8/KpilKn8zTCLj+RjpYDF6qdj5uzwK9hplZbchLX8ZRuoJ8J0DXrfpNE1vVQ4z8bnJbuutcQmAxZdPk9C3iWxUOjpXbYPX635+DC+ibDfRWT1gqJTOakeIsM77vADrSIKB0n/dvB6IK9Kf4HAOeovLrKWN2TReDSdSagJcFyncybA01imXK9FP62mPobc5EVxoVrpQvE14uEzF+KMh5hE0P3cuznlm6CU9K3jJrPc8j5ERM5UcBnD38h1dzBEXxc9+T6TC+E=
